// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYoByiQtdAPGjrg9H7hi2UcnMVztuWbmM',
    appId: '1:941959764202:web:0b2a685521e1350f845f93',
    messagingSenderId: '941959764202',
    projectId: 'inventoriumapp-test',
    authDomain: 'inventoriumapp-test.firebaseapp.com',
    storageBucket: 'inventoriumapp-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGAFFLvrSnfG4QxhRViRAsEf8ZMvam3rw',
    appId: '1:39408025622:android:fe272c3f4c4b1c7faff537',
    messagingSenderId: '39408025622',
    projectId: 'inventoriumapp',
    storageBucket: 'inventoriumapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSE8FwYRM6P3h4OnPqo-hg2vIBMKyylho',
    appId: '1:39408025622:ios:2cb2262f56ae9746aff537',
    messagingSenderId: '39408025622',
    projectId: 'inventoriumapp',
    storageBucket: 'inventoriumapp.firebasestorage.app',
    iosBundleId: 'com.example.inventorium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSE8FwYRM6P3h4OnPqo-hg2vIBMKyylho',
    appId: '1:39408025622:ios:2cb2262f56ae9746aff537',
    messagingSenderId: '39408025622',
    projectId: 'inventoriumapp',
    storageBucket: 'inventoriumapp.firebasestorage.app',
    iosBundleId: 'com.example.inventorium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2X6zDljkIMRtwKCj-S56Z_tqYPFl_Izg',
    appId: '1:39408025622:web:1b6efaae975f5353aff537',
    messagingSenderId: '39408025622',
    projectId: 'inventoriumapp',
    authDomain: 'inventoriumapp.firebaseapp.com',
    storageBucket: 'inventoriumapp.firebasestorage.app',
    measurementId: 'G-MZ6D2227FM',
  );

}